### ISSUE TITLE
Minify doesn't remove comments with exclamation marks in CSS

### ISSUE THREAD

**Issue by zcraber** [coderaiser/minify#130]
Minify version: `11.4.1`

`style.css`
```css
body {
    color: red;
}

/*!
 * comments
 * comments
 * comments
 * comments
 * comments
 */
```

`style.min.css`

```css
body{color:red}/*!
 * comments
 * comments
 * comments
 * comments
 * comments
 */

```
