### ISSUE TITLE
Problem with nesting rules

### ISSUE THREAD

**Issue by franck-paul** [coderaiser/minify#136]
The source CSS file is as below:

```css
.tidy_swap {
  margin-block-end: 0.5em;
  padding: 0.125em;

  color: var(--submit-color);
  background: var(--submit-background);

  &:is(:hover, :focus) {
    color: var(--submit-background);
    background: var(--submit-color);
  }
}
````

I run the command `minify test.css > test.min.css` and the result is as below:

```css
.tidy_swap{margin-block-end:0.5em;padding:.125em;color:var(--submit-color);background:var(--submit-background)}
````

The `&:is(…)` is missing.

**Comment by coderaiser** [comment]
Could you please try to create `.minfy.json` with:

```json
{
    "css": {
        "type": "lightningcss"
    }
}
```

And check if it works for you

**Comment by franck-paul** [comment]
Result:

```css
.foo{color:red}
````

Weird, isn'it?
